project:
  type: website
  output-dir: docs

lang: en
  

website:
  favicon: kirby1.png
  google-analytics:
    tracking-id: "G-2VZVNV14SN"
  site-url: https://crisnavarrete.github.io/cnavarrete/
  repo-url: https://github.com/crisnavarrete/cnavarrete
  navbar:
    background: none
    search: true
    collapse-below: lg
    pinned: false
    logo: logo.png
    logo-width: 250 px
    logo-heigth: auto
    left:
      - text: "HOME"
        file: index.qmd
      - posts.qmd
      - text: "PUBLICATIONS"
        file: publications.qmd
      - classes.qmd
      - href: NavarreteC_CV.pdf
        text: CV
    right: 
      - icon: twitter
        href: https://twitter.com/navarreteoya
      - icon: github
        href: https://github.com/crisnavarrete 
      - text: "{{< fa brands researchgate size=lg >}}"
        href: https://www.researchgate.net/profile/Cristian-Navarrete-3
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0001-5900-5373 
  page-footer: 
    background: primary
    center: 
      - text: "{{< fa plug size=lg >}} Powered by Quarto"
        href: https://quarto.org 

format:
  html:
    theme: darkly
    toc: true
    code-copy: true
    code-link: true
    anchor-sections: true
    code-overflow: wrap
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    css: style.css
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px

editor: visual

