project:
  type: website
  output-dir: docs
  

website:
  favicon: kirby1.png
  navbar:
    background: primary
    logo: kirby2.png
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - posts.qmd
      - text: "Publications"
        file: publications.qmd
      - href: CV_NavarreteC.pdf
        text: CV
  site-url: https://crisnavarrete.github.io/cnavarrete/
  twitter-card:
    creator: "@navarreteoya"
        
  page-footer: 
    background: primary
    left: 
      - text: "También me encuentras aquí"
      - icon: github
        href: https://github.com/crisnavarrete
      - icon: linkedin
        href: linkedin.com/in/cristian-navarrete-116623216
      - icon: twitter
        href: https://twitter.com/navarreteoya

format:
  html:
    theme:
      - style.scss
    toc: true


editor: visual

